// Surah meanings for localization. English from the standard list,
// Russian translations of the names. Used as "Al-Baqara (Корова)".
// number -> { en, ru }
export const SURAH_MEANINGS = {
  1: { en: 'The Opening', ru: 'Открывающая' },
  2: { en: 'The Cow', ru: 'Корова' },
  3: { en: 'Family of Imran', ru: 'Семейство Имрана' },
  4: { en: 'The Women', ru: 'Женщины' },
  5: { en: 'The Table Spread', ru: 'Трапеза' },
  6: { en: 'The Cattle', ru: 'Скот' },
  7: { en: 'The Heights', ru: 'Преграды' },
  8: { en: 'The Spoils of War', ru: 'Добыча' },
  9: { en: 'The Repentance', ru: 'Покаяние' },
  10: { en: 'Jonah', ru: 'Юнус' },
  11: { en: 'Hud', ru: 'Худ' },
  12: { en: 'Joseph', ru: 'Юсуф' },
  13: { en: 'The Thunder', ru: 'Гром' },
  14: { en: 'Abraham', ru: 'Ибрахим' },
  15: { en: 'The Rocky Tract', ru: 'Хиджр' },
  16: { en: 'The Bee', ru: 'Пчёлы' },
  17: { en: 'The Night Journey', ru: 'Ночной перенос' },
  18: { en: 'The Cave', ru: 'Пещера' },
  19: { en: 'Mary', ru: 'Марьям' },
  20: { en: 'Ta-Ha', ru: 'Та Ха' },
  21: { en: 'The Prophets', ru: 'Пророки' },
  22: { en: 'The Pilgrimage', ru: 'Паломничество' },
  23: { en: 'The Believers', ru: 'Верующие' },
  24: { en: 'The Light', ru: 'Свет' },
  25: { en: 'The Criterion', ru: 'Различение' },
  26: { en: 'The Poets', ru: 'Поэты' },
  27: { en: 'The Ant', ru: 'Муравьи' },
  28: { en: 'The Stories', ru: 'Рассказ' },
  29: { en: 'The Spider', ru: 'Паук' },
  30: { en: 'The Romans', ru: 'Римляне' },
  31: { en: 'Luqman', ru: 'Лукман' },
  32: { en: 'The Prostration', ru: 'Земной поклон' },
  33: { en: 'The Combined Forces', ru: 'Союзники' },
  34: { en: 'Sheba', ru: 'Саба' },
  35: { en: 'Originator', ru: 'Творец' },
  36: { en: 'Ya-Sin', ru: 'Йа Син' },
  37: { en: 'Those who set the Ranks', ru: 'Выстроившиеся в ряды' },
  38: { en: 'Sad', ru: 'Сад' },
  39: { en: 'The Troops', ru: 'Толпы' },
  40: { en: 'The Forgiver', ru: 'Прощающий' },
  41: { en: 'Explained in Detail', ru: 'Разъяснены' },
  42: { en: 'The Consultation', ru: 'Совет' },
  43: { en: 'The Ornaments of Gold', ru: 'Украшения' },
  44: { en: 'The Smoke', ru: 'Дым' },
  45: { en: 'The Crouching', ru: 'Коленопреклонённые' },
  46: { en: 'The Wind-Curved Sandhills', ru: 'Барханы' },
  47: { en: 'Muhammad', ru: 'Мухаммад' },
  48: { en: 'The Victory', ru: 'Победа' },
  49: { en: 'The Rooms', ru: 'Комнаты' },
  50: { en: 'Qaf', ru: 'Каф' },
  51: { en: 'The Winnowing Winds', ru: 'Рассеивающие' },
  52: { en: 'The Mount', ru: 'Гора' },
  53: { en: 'The Star', ru: 'Звезда' },
  54: { en: 'The Moon', ru: 'Луна' },
  55: { en: 'The Beneficent', ru: 'Милостивый' },
  56: { en: 'The Inevitable', ru: 'Событие' },
  57: { en: 'The Iron', ru: 'Железо' },
  58: { en: 'The Pleading Woman', ru: 'Препирательство' },
  59: { en: 'The Exile', ru: 'Сбор' },
  60: { en: 'She that is to be Examined', ru: 'Испытуемая' },
  61: { en: 'The Ranks', ru: 'Ряды' },
  62: { en: 'The Congregation', ru: 'Собрание' },
  63: { en: 'The Hypocrites', ru: 'Лицемеры' },
  64: { en: 'The Mutual Disillusion', ru: 'Взаимное обделение' },
  65: { en: 'The Divorce', ru: 'Развод' },
  66: { en: 'The Prohibition', ru: 'Запрещение' },
  67: { en: 'The Sovereignty', ru: 'Власть' },
  68: { en: 'The Pen', ru: 'Письменная трость' },
  69: { en: 'The Reality', ru: 'Неминуемое' },
  70: { en: 'The Ascending Stairways', ru: 'Ступени' },
  71: { en: 'Noah', ru: 'Нух' },
  72: { en: 'The Jinn', ru: 'Джинны' },
  73: { en: 'The Enshrouded One', ru: 'Закутавшийся' },
  74: { en: 'The Cloaked One', ru: 'Завернувшийся' },
  75: { en: 'The Resurrection', ru: 'Воскресение' },
  76: { en: 'Man', ru: 'Человек' },
  77: { en: 'The Emissaries', ru: 'Посылаемые' },
  78: { en: 'The Tidings', ru: 'Весть' },
  79: { en: 'Those who drag forth', ru: 'Вырывающие' },
  80: { en: 'He Frowned', ru: 'Нахмурился' },
  81: { en: 'The Overthrowing', ru: 'Скручивание' },
  82: { en: 'The Cleaving', ru: 'Раскалывание' },
  83: { en: 'The Defrauding', ru: 'Обвешивающие' },
  84: { en: 'The Splitting Open', ru: 'Разверзнется' },
  85: { en: 'The Mansions of the Stars', ru: 'Созвездия' },
  86: { en: 'The Morning Star', ru: 'Ночной путник' },
  87: { en: 'The Most High', ru: 'Всевышний' },
  88: { en: 'The Overwhelming', ru: 'Покрывающее' },
  89: { en: 'The Dawn', ru: 'Заря' },
  90: { en: 'The City', ru: 'Город' },
  91: { en: 'The Sun', ru: 'Солнце' },
  92: { en: 'The Night', ru: 'Ночь' },
  93: { en: 'The Morning Hours', ru: 'Утро' },
  94: { en: 'The Relief', ru: 'Раскрытие' },
  95: { en: 'The Fig', ru: 'Смоковница' },
  96: { en: 'The Clot', ru: 'Сгусток' },
  97: { en: 'The Power', ru: 'Предопределение' },
  98: { en: 'The Clear Proof', ru: 'Ясное знамение' },
  99: { en: 'The Earthquake', ru: 'Сотрясение' },
  100: { en: 'The Courser', ru: 'Скачущие' },
  101: { en: 'The Calamity', ru: 'Великое бедствие' },
  102: { en: 'The Rivalry in world increase', ru: 'Страсть к приумножению' },
  103: { en: 'The Declining Day', ru: 'Время' },
  104: { en: 'The Traducer', ru: 'Хулитель' },
  105: { en: 'The Elephant', ru: 'Слон' },
  106: { en: 'Quraysh', ru: 'Курайшиты' },
  107: { en: 'The Small Kindnesses', ru: 'Подаяние' },
  108: { en: 'The Abundance', ru: 'Изобилие' },
  109: { en: 'The Disbelievers', ru: 'Неверующие' },
  110: { en: 'The Divine Support', ru: 'Помощь' },
  111: { en: 'The Palm Fiber', ru: 'Пальмовые волокна' },
  112: { en: 'The Sincerity', ru: 'Искренность' },
  113: { en: 'The Daybreak', ru: 'Рассвет' },
  114: { en: 'Mankind', ru: 'Люди' },
};

export function surahMeaning(number, lang) {
  const m = SURAH_MEANINGS[number];
  if (!m) return '';
  return lang === 'ru' ? m.ru : m.en;
}
